services:
  - type: web
    name: hospital-management-system
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    disk:
      name: hospital-data
      mountPath: /var/lib/sqlite
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true
